name: Test

on:
  pull_request:
    branches: [develop, main]

jobs:
  php-unit:
    name: PHP Unit | Shopware ${{ matrix.shopware }} / PHP ${{ matrix.php }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [8.2, 8.3]
        shopware: [6.6, 6.7]

    steps:
      - uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, xml, ctype, iconv, intl, json, pdo, zip, bcmath
          tools: composer

      - name: Patch composer.json to test matrix version
        run: |
          sed -i 's/"shopware\/core": "[^"]*"/"shopware\/core": "^${{ matrix.shopware }}"/' composer.json

      - name: Install dependencies
        uses: ramsey/composer-install@v3
        with:
          composer-options: --no-scripts --prefer-dist

      - name: Run Unit Tests
        run: ./vendor/bin/phpunit --configuration phpunit.xml.dist

      - name: Validate Plugin
        uses: FriendsOfShopware/shopware-cli-action@v1
        with:
          command: extension validate .

  cypress-e2e:
    name: Cypress E2E | Shopware ${{ matrix.shopware }} / PHP ${{ matrix.php }}
    needs: php-unit
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [8.2, 8.3]
        shopware: [6.6.0.0, 6.7.0.0]

    steps:
      - name: Checkout Plugin
        uses: actions/checkout@v4

      - name: Start Dockware container
        run: |
          docker run -d --name dockware \
            -p 80:80 \
            -e XDEBUG_ENABLED=0 \
            dockware/play:${{ matrix.shopware }}
          
          echo "Waiting for Dockware to boot..."
          until curl -sSf http://localhost > /dev/null; do
            sleep 5
          done

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Cypress dependencies
        run: npm install

      - name: Copy and patch plugin in container
        run: |
          PLUGIN_NAME=$(ls src | head -n 1)
          docker cp ./src/$PLUGIN_NAME dockware:/var/www/html/custom/plugins/$PLUGIN_NAME
          
          # Patch composer.json in the container
          docker exec dockware bash -c "sed -i 's/\"shopware\\/core\": \\\"[^\"]*\\\"/\"shopware\\/core\": \\\"^${{ matrix.shopware }}\\\"/' /var/www/html/custom/plugins/$PLUGIN_NAME/composer.json"
          
          # Optional: re-require in container to ensure correct deps (fail silently if already met)
          docker exec dockware bash -c "cd /var/www/html && composer require shopware/core:^${{ matrix.shopware }} --no-interaction || true"
          
          # Install & activate plugin
          docker exec dockware bash -c "bin/console plugin:refresh"
          docker exec dockware bash -c "bin/console plugin:install --activate $PLUGIN_NAME"
          docker exec dockware bash -c "bin/console cache:clear"

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          wait-on: 'http://localhost'
          wait-on-timeout: 120