name: Test

on:
  pull_request:
    branches: [develop, main]

jobs:
  php-unit:
    name: PHP Unit | Shopware ${{ matrix.shopware }} / PHP ${{ matrix.php }}
    runs-on: ubuntu-latest
    needs: cypress-e2e
    strategy:
      fail-fast: false
      matrix:
        php: [8.2, 8.3]
        shopware: [6.6, 6.7]

    steps:
      - uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, xml, ctype, iconv, intl, json, pdo, zip, bcmath
          tools: composer

      - name: Patch composer.json to test matrix version
        run: |
          sed -i 's/"shopware\/core": "[^"]*"/"shopware\/core": "^${{ matrix.shopware }}"/' composer.json

      - name: Install dependencies
        uses: ramsey/composer-install@v3
        with:
          composer-options: --no-scripts --prefer-dist

      - name: Run Unit Tests
        run: ./vendor/bin/phpunit --configuration phpunit.xml.dist

      - name: Validate Plugin
        uses: FriendsOfShopware/shopware-cli-action@v1
        with:
          command: extension validate .

  cypress-e2e:
    name: Cypress E2E | Shopware ${{ matrix.shopware }} / PHP ${{ matrix.php }}
    #needs: php-unit
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [8.2, 8.3]
        shopware: [6.6.0.0, 6.7.0.0]

    steps:
      - name: Checkout Plugin
        uses: actions/checkout@v4

      - name: Start Dockware container
        run: |
          docker run -d --name dockware \
            -p 80:80 \
            -e XDEBUG_ENABLED=0 \
            dockware/play:${{ matrix.shopware }}
          
          echo "Waiting for Dockware to boot..."
          until curl -sSf http://localhost > /dev/null; do
            sleep 5
          done

      - name: Patch composer.json to test matrix version
        run: |
          sed -i 's/"shopware\/core": "[^"]*"/"shopware\/core": "^${{ matrix.shopware }}"/' composer.json

      - name: Copy and patch plugin in container
        run: |
          ls -la
          docker cp ./ dockware:/var/www/html/custom/plugins/NeonlinesMinimalPlugin
          docker exec shop bash -c 'sudo chown www-data:www-data /var/www/html/custom/plugins -R'
                    
          # Install & activate plugin
          docker exec dockware bash -c "bin/console plugin:refresh"
          docker exec dockware bash -c "bin/console plugin:install --activate NeonlinesMinimalPlugin"
          docker exec dockware bash -c "bin/console cache:clear"
          
          cd ./plugin/tests/Cypress 
          docker run --network host -v $PWD:/e2e -w /e2e -e CYPRESS_BASE_URL=http://localhost cypress/included:10.8.0