name: Test

on:
  pull_request:
    branches: [develop, main]

jobs:
  php-unit:
    name: PHP Unit | Shopware ${{ matrix.shopware }} / PHP ${{ matrix.php }}
    runs-on: ubuntu-latest
    needs: cypress-e2e
    strategy:
      fail-fast: false
      matrix:
        php: [8.2, 8.3]
        shopware: [6.6, 6.7]

    steps:
      - uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, xml, ctype, iconv, intl, json, pdo, zip, bcmath
          tools: composer

      - name: Patch composer.json to test matrix version
        run: |
          sed -i 's/"shopware\/core": "[^"]*"/"shopware\/core": "^${{ matrix.shopware }}"/' composer.json

      - name: Install dependencies
        uses: ramsey/composer-install@v3
        with:
          composer-options: --no-scripts --prefer-dist

      - name: Run Unit Tests
        run: ./vendor/bin/phpunit --configuration phpunit.xml.dist

      - name: Validate Plugin
        uses: FriendsOfShopware/shopware-cli-action@v1
        with:
          command: extension validate .

  cypress-e2e:
    name: E2E Tests | Shopware ${{ matrix.shopware }}, PHP ${{ matrix.php }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - shopware: '6.4.7.0'
            php: '8.0'
          - shopware: '6.4.6.1'
            php: '8.0'
          - shopware: '6.4.5.1'
            php: '7.4'
    steps:

      - name: Clone Code
        uses: actions/checkout@v4

      - name: Download Docker
        run: |
          docker pull dockware/dev:${{ matrix.shopware }}

      - name: Start Docker
        run: |
          docker run --rm -p 80:80 -p 443:443 --name shop --env PHP_VERSION=${{ matrix.php }} -d dockware/dev:${{ matrix.shopware }}
          sleep 30
          docker logs shop
          # now change the domain of our shop if required
          sudo echo "127.0.0.1 local.shopware.shop" | sudo tee -a /etc/hosts
          docker exec shop bash -c "mysql -u root -proot shopware -e \"UPDATE sales_channel_domain SET url='https://local.shopware.shop' WHERE url NOT LIKE 'default.%';\""

      - name: Patch composer.json to test matrix version
        run: |
          sed -i 's/"shopware\/core": "[^"]*"/"shopware\/core": "^${{ matrix.shopware }}"/' composer.json

      - name: Upload into Docker
        run: |
          docker cp $(pwd)/. shop:/var/www/html/custom/plugins/NeonlinesMinimalPlugin
          docker exec shop bash -c 'sudo chown www-data:www-data /var/www/html/custom/plugins -R'

      - name: Install/Configure Plugin
        run: |
          docker exec shop bash -c 'php bin/console plugin:refresh'
          docker exec shop bash -c 'php bin/console plugin:install NeonlinesMinimalPlugin --activate'
          docker exec shop bash -c 'php bin/console cache:clear'

      - name: Install Cypress
        run: cd tests/Cypress && make install -B

      - name: Start Cypress
        run: cd tests/Cypress && CYPRESS_BASE_URL=http://local.shopware.shop CYPRESS_SHOPWARE=${{ matrix.shopware }} ./node_modules/.bin/cypress run --headless

      - name: Download Logs
        if: ${{ always() }}
        run: |
          mkdir -p $(pwd)/Tests/Cypress/cypress/logs/shopware
          mkdir -p $(pwd)/Tests/Cypress/cypress/logs/apache
          docker cp shop:/var/www/html/var/log/. $(pwd)/Tests/Cypress/cypress/logs/shopware
          docker cp shop:/var/log/php/. $(pwd)/Tests/Cypress/cypress/logs/apache

      - name: Store Cypress Results
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: cypress_results_sw_v${{ matrix.shopware }}
          retention-days: 1
          path: |
            Tests/Cypress/cypress/logs
            Tests/Cypress/cypress/videos
            Tests/Cypress/cypress/screenshots